version: '3'
services:
  django-backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/db  # Mount volume for SQLite file

  vue-frontend:
    build: ./ticketfront
    ports:
      - "3000:3000"
    # No need to depend on django-backend
