# Generated by Django 4.2.16 on 2024-09-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
